### ISSUE TITLE
[Issues] : Wrong DOM validate nesting.

### ISSUE THREAD

**Issue by prasetyodimas** [prasetyodimas/prasetyodev#15]
Please be aware :

Description of the issues :

1. When you check this website and start localy or test at the server the error appear at the console browser, see below the detail error log.

```
head-export-handler-for-browser.js:72 Warning: validateDOMNesting(...): <a> cannot appear as a descendant of <a>.
    at a
    at eval (webpack-internal:///./node_modules/@gatsbyjs/reach-router/dist/index.modern.mjs:36:6406)
    at P (webpack-internal:///./node_modules/gatsby-link/dist/index.modern.mjs:14:2026)
    at G (webpack-internal:///./node_modules/@gatsbyjs/reach-router/dist/index.modern.mjs:36:9074)
    at w
    at div
    at BlockElement (webpack-internal:///./src/components/blockElement.js:12:5)
    at a
    at div
    at nav
    at Navbar (webpack-internal:///./src/components/navbar.js:37:12)
    at Layout (webpack-internal:///./src/components/layout.js:23:5)
    at IndexSite (webpack-internal:///./src/pages/index.js?export=default:17:5)
    at PageRenderer (webpack-internal:///./.cache/page-renderer.js:24:76)
    at PageQueryStore (webpack-internal:///./.cache/query-result-store.js:35:30)
    at RouteHandler
    at div
    at re (webpack-internal:///./node_modules/@gatsbyjs/reach-router/dist/index.modern.mjs:36:9865)
    at ee (webpack-internal:///./node_modules/@gatsbyjs/reach-router/dist/index.modern.mjs:36:9680)
    at ae (webpack-internal:///./node_modules/@gatsbyjs/reach-router/dist/index.modern.mjs:36:10957)
    at oe (webpack-internal:///./node_modules/@gatsbyjs/reach-router/dist/index.modern.mjs:36:10831)
    at ScrollHandler (webpack-internal:///./node_modules/gatsby-react-router-scroll/scroll-handler.js:23:35)
    at RouteUpdates (webpack-internal:///./.cache/navigation.js:253:32)
    at EnsureResources (webpack-internal:///./.cache/ensure-resources.js:19:30)
    at LocationHandler (webpack-internal:///./.cache/root.js:62:29)
    at eval (webpack-internal:///./node_modules/@gatsbyjs/reach-router/dist/index.modern.mjs:36:8283)
    at F (webpack-internal:///./node_modules/@gatsbyjs/reach-router/dist/index.modern.mjs:36:7181)
    at H (webpack-internal:///./node_modules/@gatsbyjs/reach-router/dist/index.modern.mjs:36:7483)
    at WithErrorBoundary()
    at G (webpack-internal:///./node_modules/@gatsbyjs/reach-router/dist/index.modern.mjs:36:9074)
    at Root
    at StaticQueryStore (webpack-internal:///./.cache/query-result-store.js:130:32)
    at SliceDataStore (webpack-internal:///./.cache/query-result-store.js:177:32)
    at ErrorBoundary (webpack-internal:///./.cache/fast-refresh-overlay/components/error-boundary.js:21:35)
    at DevOverlay (webpack-internal:///./.cache/fast-refresh-overlay/index.js:119:5)
    at RootWrappedWithOverlayAndProvider
    at App (webpack-internal:///./.cache/app.js:167:80)
```
Issues at the console : 

Explanation :
1. Check element every page when have html in jsx format not valid nesting DOM element.

**Comment by prasetyodimas** [comment]
Solved !
