### ISSUE TITLE
[Issues] Error at Console Uncaught Error: Minified React error #418

### ISSUE THREAD

**Issue by prasetyodimas** [prasetyodimas/prasetyodev#18]
Please be aware :

Description of the issues :

Explanation :
When visited landing page https://prasetyodev.gatsbyjs.io/ -> see and check at developer tools

5react-dom.production.min.js:131 Uncaught Error: Minified React error #418; visit https://reactjs.org/docs/error-decoder.html?invariant=418 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at sa (react-dom.production.min.js:131:278)
    at Ei (react-dom.production.min.js:293:379)
    at ks (react-dom.production.min.js:280:389)
    at ys (react-dom.production.min.js:280:320)
    at gs (react-dom.production.min.js:280:180)
    at as (react-dom.production.min.js:268:209)
    at S (scheduler.production.min.js:13:203)
    at MessagePort.T (scheduler.production.min.js:14:128)

**Comment by prasetyodimas** [comment]
The error message **"Uncaught Error: Minified React error"** typically indicates that there's an issue with your React application. The error message is intentionally minified in production builds for better performance, so it might not provide a lot of details on the exact problem.

Here are some general steps you can take to troubleshoot and fix this issue:

Check the Browser Console:
Open your browser's developer tools and check the console for more detailed error messages. There might be additional information that can help you identify the specific problem.

**Source Maps:**
If you're using a minified production build of your React application, make sure that you have source maps enabled. Source maps allow you to map the minified code back to the original source code, making it easier to debug.

**Review Recent Changes:**
If the error started occurring after making changes to your code, review those changes carefully. Look for typos, missing imports, or any other potential issues.

**Check Dependencies:**
Ensure that your React and related dependencies (like ReactDOM) are up to date. Sometimes, incompatibilities between different versions can lead to errors.

**Debugging in Development Mode:**
If the issue only occurs in production, try reproducing it in development mode. Development builds provide more helpful error messages that can assist in identifying the problem.

**Check for Runtime Errors:**
Look for any runtime errors in your code. Incorrectly used hooks, missing dependencies, or other runtime issues can cause this type of error.

**Review Component Rendering:**
Check the rendering logic of your components. Make sure that all components are being rendered correctly and that there are no infinite loops or other issues.

**Webpack or Other Bundler Configuration:**
If you're using Webpack or another bundler, check the configuration to ensure it's set up correctly, especially if you're using any plugins for minification.

**Browser Cache:**
Clear your browser cache and try reloading the application. Sometimes, cached files can cause unexpected issues.

**Network Issues:**
Ensure that all the necessary files (JavaScript bundles, CSS files, etc.) are successfully loaded. Network issues could prevent the correct loading of these resources.


Solved ! [Close this issues] Cheers !
